services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - RATE_LIMIT_IP=5
      - RATE_LIMIT_TOKEN=10
      - BLOCK_DURATION=60
    ports:
      - "8080:8080"
    depends_on:
      - redis
